const SINS = [
  {
    id: 'avarice',
    name: 'Avarice',
    title: "L'Insatiable Avare",
    number: '01',
    color: '#FFD220',
    colorRGB: '255,210,32',
    description: "Ici, l'Avarice est représentée par un homme face à des montagnes de ressources. Il a les bras tendus vers ce qu'il convoite et semble tout acquérir sans en perdre une miette. Il est ambitieux et déterminé à faire, être et avoir mieux. Serait-ce à sa perte ?",
    concept: "La mise en scène de l'accumulation. Des objets, des richesses, empilés comme des trophées. L'avarice n'est pas le besoin — c'est la peur de manquer, transformée en obsession de posséder.",
    intention: "Ici, l'Avarice est représentée par un homme face à des montagnes de ressources. Il a les bras tendus vers ce qu'il convoite et semble tout acquérir sans en perdre une miette.",
    intentionSub: "Il est ambitieux et déterminé à faire, être et avoir mieux. Serait-ce à sa perte ?",
    imageV1: 'images/avarice-v1.jpg',
    imageFinale: 'images/Avarice%20(v4).jpg',
    moodboard: 'images/moodboard-avarice.png',
  },
  {
    id: 'colere',
    name: 'Colère',
    title: "Colère Implosive d'une IA",
    number: '02',
    color: '#D90E15',
    colorRGB: '217,14,21',
    description: "Ici, la Colère est représentée à travers un homme qui ne sait plus se comporter autrement que comme l'IA. Ceci est mis en exergue grâce au texte : « Désolé, je ne suis pas sûr de comprendre ».",
    concept: "La colère a été photographiée non pas dans son paroxysme, mais dans ses traces. Après la tempête, quand la rage a laissé place à un silence tendu. La destruction silencieuse.",
    intention: "Ici, la Colère est représentée à travers un homme qui ne sait plus se comporter autrement que comme l'IA.",
    intentionSub: "Ceci est mis en exergue grâce au texte : « Désolé, je ne suis pas sûr de comprendre ».",
    imageV1: 'images/colere-v1.jpg',
    imageFinale: 'images/Col%C3%A8re%20v(4).jpg',
    moodboard: 'images/moodboard-colere.png',
  },
  {
    id: 'envie',
    name: 'Envie',
    title: 'Envie Maladive',
    number: '03',
    color: '#438B37',
    colorRGB: '67,139,55',
    description: "Ici, l'Envie est représentée par un homme s'accoudant au rebord de son miroir ; en train de fixer son reflet, sa version « parfaite ». Cette photographie met en lumière la fixation sur le fait d'atteindre la perfection physique et mentale.",
    concept: "L'envie se lit dans un regard dirigé vers l'ailleurs. Le sujet est présent, mais son attention est captée par quelque chose — quelqu'un — hors cadre. La convoitise est dans cet espace manquant.",
    intention: "Ici, l'Envie est représentée par un homme s'accoudant au rebord de son miroir ; en train de fixer son reflet, sa version « parfaite ».",
    intentionSub: "Cette photographie met en lumière la fixation sur le fait d'atteindre la perfection physique et mentale.",
    imageV1: 'images/envie-v1.jpg',
    imageFinale: 'images/Envie%20(v4)%20.jpg',
    moodboard: 'images/moodboard-envie.png',
  },
  {
    id: 'gourmandise',
    name: 'Gourmandise',
    title: 'Irrémédiable Gourmandise',
    number: '04',
    color: '#7B170F',
    colorRGB: '123,23,15',
    description: "Ici, la Gourmandise est représentée à travers une femme qui se rue sur des pâtisseries servies sur un plateau par un robot IA. Cette photographie met en avant l'envie démesurée de consommer, au-delà des besoins physiologiques.",
    concept: "Une composition saturée, presque excessive. Les textures, les couleurs, l'abondance — tout est amplifié jusqu'à l'inconfort. La gourmandise comme état d'ébriété sensorielle.",
    intention: "Ici, la Gourmandise est représentée à travers une femme qui se rue sur des pâtisseries servies sur un plateau par un robot IA.",
    intentionSub: "Cette photographie met en avant l'envie démesurée de consommer, au-delà des besoins physiologiques.",
    imageV1: 'images/gourmandise-v1.jpg',
    imageFinale: 'images/Gourmandise%20(v4).jpg',
    moodboard: 'images/moodboard-gourmandise.png',
  },
  {
    id: 'luxure',
    name: 'Luxure',
    title: "L'Amorale Luxure",
    number: '05',
    color: '#EB9BC3',
    colorRGB: '235,155,195',
    description: "Ici, la Luxure est représentée par une femme et une IA dans la pénombre. Les deux s'observent et luttent contre leurs dernières réserves. Cette photographie met en avant la recherche d'acte charnel immoral, comme ici la liaison entre IA et humain.",
    concept: "La luxure est photographiée dans le registre du suggestif. Ni explicite ni absent — dans l'espace de tension entre voile et révélation. La lumière devient complice.",
    intention: "Ici, la Luxure est représentée par une femme et une IA dans la pénombre. Les deux s'observent et luttent contre leurs dernières réserves.",
    intentionSub: "Cette photographie met en avant la recherche d'acte charnel immoral, comme ici la liaison entre IA et humain.",
    imageV1: 'images/luxure-v1.jpg',
    imageFinale: 'images/Luxure%20(v4).jpg',
    moodboard: 'images/moodboard-luxure.png',
  },
  {
    id: 'orgueil',
    name: 'Orgueil',
    title: "L'Hégémonique Orgueilleux",
    number: '06',
    color: '#D58553',
    colorRGB: '213,133,83',
    description: "Ici, l'Orgueil est représenté par un homme assis de façon hautaine sur le dos d'une personne, tout en manipulant un jeune homme lui servant de marionnette. Cette image met en exergue l'envie néfaste que l'Homme peut avoir à vouloir exercer du contrôle sur autrui.",
    concept: "Une composition frontale, symétrique, dominante. L'orgueil occupe tout l'espace. Rien n'existe autour du sujet — il est le centre absolu de son propre monde.",
    intention: "Ici, l'Orgueil est représenté par un homme assis de façon hautaine sur le dos d'une personne, tout en manipulant un jeune homme lui servant de marionnette.",
    intentionSub: "Cette image met en exergue l'envie néfaste que l'Homme peut avoir à vouloir exercer du contrôle sur autrui.",
    imageV1: 'images/orgueil-v1.jpg',
    imageFinale: 'images/Orgueil%20(v4).jpg',
    moodboard: 'images/moodboard-orgueil.png',
  },
  {
    id: 'paresse',
    name: 'Paresse',
    title: 'Le Paresseux Sclérosé',
    number: '07',
    color: '#76B2E1',
    colorRGB: '118,178,225',
    description: "Ici, la Paresse est représentée à travers un homme qui ne sait plus se passer de l'IA, au point que son oisiveté triomphe sur qui il est dans sa singularité. Le titre évoque le fait qu'avec l'IA, il ne progresse plus, n'apprend plus et n'évolue plus.",
    concept: "La paresse n'est pas l'absence d'action — c'est la résignation active. Le corps qui refuse de se lever, non par manque de force, mais par désintérêt pour le monde.",
    intention: "Ici, la Paresse est représentée à travers un homme qui ne sait plus se passer de l'IA, au point que son oisiveté triomphe sur qui il est dans sa singularité.",
    intentionSub: "Le titre évoque le fait qu'avec l'IA, il ne progresse plus, n'apprend plus et n'évolue plus.",
    imageV1: 'images/paresse-v1.jpg',
    imageFinale: 'images/Paresse%20(v4).jpg',
    moodboard: 'images/moodboard-paresse.png',
  },
];

function getSinById(id) {
  return SINS.find(s => s.id === id) || null;
}

function getSinByIndex(index) {
  return SINS[((index % SINS.length) + SINS.length) % SINS.length];
}
